-- MySQL Script generated by MySQL Workbench
-- Mon Apr 21 12:27:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ait127810
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ait127810
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ait127810` DEFAULT CHARACTER SET utf8 ;
USE `ait127810` ;

-- -----------------------------------------------------
-- Table `ait127810`.`billing_adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`billing_adress` (
  `order_id` INT NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `street_number` VARCHAR(3) NOT NULL,
  `apartment_number` VARCHAR(3) NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` VARCHAR(50) NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_billing_adress_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ait127810`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ait127810`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`cart` (
  `user_id` INT NOT NULL,
  INDEX `fk_cart_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ait127810`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ait127810`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`cart_items` (
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`cart_id`, `product_id`),
  INDEX `fk_cart_items_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_cart_items_cart1_idx` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_items_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ait127810`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_items_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `ait127810`.`cart` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ait127810`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `ait127810`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(10) NOT NULL,
  `total_amount` DECIMAL(9,2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `order_number_UNIQUE` (`order_number` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ait127810`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ait127810`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`order_items` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_order_jtem_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_items_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_jtem_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ait127810`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ait127810`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ait127810`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(50) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `short_name_UNIQUE` (`short_name` ASC) VISIBLE,
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ait127810`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ait127810`.`product_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`product_details` (
  `product_id` INT NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `short_name_UNIQUE` (`full_name` ASC) VISIBLE,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_details_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ait127810`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ait127810`.`shipping_adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`shipping_adress` (
  `order_id` INT NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `street_number` VARCHAR(3) NOT NULL,
  `apartment_number` VARCHAR(3) NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` VARCHAR(50) NULL,
  INDEX `fk_shipping_adress_order1_idx` (`order_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_shipping_adress_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ait127810`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ait127810`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ait127810`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ait127810`.`user_role` (
  `user_id` INT NOT NULL,
  `authority` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ait127810`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
